/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FilmlarRouteImport } from './routes/filmlar'
import { Route as JanrlarRouteImport } from './routes/janrlar'
import { Route as QidiruvRouteImport } from './routes/qidiruv'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SaralanganlarRouteImport } from './routes/saralanganlar'
import { Route as SeriallarRouteImport } from './routes/seriallar'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as KinoIdRouteImport } from './routes/kino.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmlarRoute = FilmlarRouteImport.update({
  id: '/filmlar',
  path: '/filmlar',
  getParentRoute: () => rootRouteImport,
} as any)
const JanrlarRoute = JanrlarRouteImport.update({
  id: '/janrlar',
  path: '/janrlar',
  getParentRoute: () => rootRouteImport,
} as any)
const QidiruvRoute = QidiruvRouteImport.update({
  id: '/qidiruv',
  path: '/qidiruv',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SaralanganlarRoute = SaralanganlarRouteImport.update({
  id: '/saralanganlar',
  path: '/saralanganlar',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriallarRoute = SeriallarRouteImport.update({
  id: '/seriallar',
  path: '/seriallar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const KinoIdRoute = KinoIdRouteImport.update({
  id: '/kino/$id',
  path: '/kino/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/filmlar': typeof FilmlarRoute
  '/janrlar': typeof JanrlarRoute
  '/qidiruv': typeof QidiruvRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saralanganlar': typeof SaralanganlarRoute
  '/seriallar': typeof SeriallarRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/kino/$id': typeof KinoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/filmlar': typeof FilmlarRoute
  '/janrlar': typeof JanrlarRoute
  '/qidiruv': typeof QidiruvRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saralanganlar': typeof SaralanganlarRoute
  '/seriallar': typeof SeriallarRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/kino/$id': typeof KinoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/filmlar': typeof FilmlarRoute
  '/janrlar': typeof JanrlarRoute
  '/qidiruv': typeof QidiruvRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saralanganlar': typeof SaralanganlarRoute
  '/seriallar': typeof SeriallarRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/kino/$id': typeof KinoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/filmlar'
    | '/janrlar'
    | '/qidiruv'
    | '/reset-password'
    | '/saralanganlar'
    | '/seriallar'
    | '/profil'
    | '/kino/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/filmlar'
    | '/janrlar'
    | '/qidiruv'
    | '/reset-password'
    | '/saralanganlar'
    | '/seriallar'
    | '/profil'
    | '/kino/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/filmlar'
    | '/janrlar'
    | '/qidiruv'
    | '/reset-password'
    | '/saralanganlar'
    | '/seriallar'
    | '/_authenticated/profil'
    | '/kino/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  FilmlarRoute: typeof FilmlarRoute
  JanrlarRoute: typeof JanrlarRoute
  QidiruvRoute: typeof QidiruvRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SaralanganlarRoute: typeof SaralanganlarRoute
  SeriallarRoute: typeof SeriallarRoute
  KinoIdRoute: typeof KinoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmlar': {
      id: '/filmlar'
      path: '/filmlar'
      fullPath: '/filmlar'
      preLoaderRoute: typeof FilmlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/janrlar': {
      id: '/janrlar'
      path: '/janrlar'
      fullPath: '/janrlar'
      preLoaderRoute: typeof JanrlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qidiruv': {
      id: '/qidiruv'
      path: '/qidiruv'
      fullPath: '/qidiruv'
      preLoaderRoute: typeof QidiruvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saralanganlar': {
      id: '/saralanganlar'
      path: '/saralanganlar'
      fullPath: '/saralanganlar'
      preLoaderRoute: typeof SaralanganlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seriallar': {
      id: '/seriallar'
      path: '/seriallar'
      fullPath: '/seriallar'
      preLoaderRoute: typeof SeriallarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/kino/$id': {
      id: '/kino/$id'
      path: '/kino/$id'
      fullPath: '/kino/$id'
      preLoaderRoute: typeof KinoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  FilmlarRoute: FilmlarRoute,
  JanrlarRoute: JanrlarRoute,
  QidiruvRoute: QidiruvRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SaralanganlarRoute: SaralanganlarRoute,
  SeriallarRoute: SeriallarRoute,
  KinoIdRoute: KinoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
