/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmlarRouteImport } from './routes/filmlar'
import { Route as JanrlarRouteImport } from './routes/janrlar'
import { Route as QidiruvRouteImport } from './routes/qidiruv'
import { Route as SaralanganlarRouteImport } from './routes/saralanganlar'
import { Route as SeriallarRouteImport } from './routes/seriallar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmlarRoute = FilmlarRouteImport.update({
  id: '/filmlar',
  path: '/filmlar',
  getParentRoute: () => rootRouteImport,
} as any)
const JanrlarRoute = JanrlarRouteImport.update({
  id: '/janrlar',
  path: '/janrlar',
  getParentRoute: () => rootRouteImport,
} as any)
const QidiruvRoute = QidiruvRouteImport.update({
  id: '/qidiruv',
  path: '/qidiruv',
  getParentRoute: () => rootRouteImport,
} as any)
const SaralanganlarRoute = SaralanganlarRouteImport.update({
  id: '/saralanganlar',
  path: '/saralanganlar',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriallarRoute = SeriallarRouteImport.update({
  id: '/seriallar',
  path: '/seriallar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/filmlar': typeof FilmlarRoute
  '/janrlar': typeof JanrlarRoute
  '/qidiruv': typeof QidiruvRoute
  '/saralanganlar': typeof SaralanganlarRoute
  '/seriallar': typeof SeriallarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/filmlar': typeof FilmlarRoute
  '/janrlar': typeof JanrlarRoute
  '/qidiruv': typeof QidiruvRoute
  '/saralanganlar': typeof SaralanganlarRoute
  '/seriallar': typeof SeriallarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/filmlar': typeof FilmlarRoute
  '/janrlar': typeof JanrlarRoute
  '/qidiruv': typeof QidiruvRoute
  '/saralanganlar': typeof SaralanganlarRoute
  '/seriallar': typeof SeriallarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/filmlar' | '/janrlar' | '/qidiruv' | '/saralanganlar' | '/seriallar'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/filmlar' | '/janrlar' | '/qidiruv' | '/saralanganlar' | '/seriallar'
  id:
    | '__root__'
    | '/'
    | '/filmlar'
    | '/janrlar'
    | '/qidiruv'
    | '/saralanganlar'
    | '/seriallar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilmlarRoute: typeof FilmlarRoute
  JanrlarRoute: typeof JanrlarRoute
  QidiruvRoute: typeof QidiruvRoute
  SaralanganlarRoute: typeof SaralanganlarRoute
  SeriallarRoute: typeof SeriallarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmlar': {
      id: '/filmlar'
      path: '/filmlar'
      fullPath: '/filmlar'
      preLoaderRoute: typeof FilmlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/janrlar': {
      id: '/janrlar'
      path: '/janrlar'
      fullPath: '/janrlar'
      preLoaderRoute: typeof JanrlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qidiruv': {
      id: '/qidiruv'
      path: '/qidiruv'
      fullPath: '/qidiruv'
      preLoaderRoute: typeof QidiruvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saralanganlar': {
      id: '/saralanganlar'
      path: '/saralanganlar'
      fullPath: '/saralanganlar'
      preLoaderRoute: typeof SaralanganlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seriallar': {
      id: '/seriallar'
      path: '/seriallar'
      fullPath: '/seriallar'
      preLoaderRoute: typeof SeriallarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilmlarRoute: FilmlarRoute,
  JanrlarRoute: JanrlarRoute,
  QidiruvRoute: QidiruvRoute,
  SaralanganlarRoute: SaralanganlarRoute,
  SeriallarRoute: SeriallarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
